name: Deploy to Heroku

on:
  workflow_call:
    secrets:
      HEROKU_API:
        required: true

jobs:
  deploy:
    runs-on: ubuntu-latest

    steps:
      - name: Checkout code
        uses: actions/checkout@v4

      - name: Install Heroku CLI
        run: curl https://cli-assets.heroku.com/install.sh | sh

      - name: Log in to Heroku Container Registry
        run: |
          echo $HEROKU_API | docker login registry.heroku.com -u _ --password-stdin
        env:
          HEROKU_API: ${{ secrets.HEROKU_API }}

      - name: Build and push auth_service image
        run: |
          docker build -t registry.heroku.com/tank-auth-service/web ./auth_service
          docker push registry.heroku.com/tank-auth-service/web

      - name: Set stack to container
        run: heroku stack:set container -a tank-auth-service
        env:
          HEROKU_API_KEY: ${{ secrets.HEROKU_API }}

      - name: Release auth_service
        run: heroku container:release web -a tank-auth-service
        env:
          HEROKU_API_KEY: ${{ secrets.HEROKU_API }}
