name: Test Docker Build

on:
  workflow_call:

jobs:
  build-and-test:
    runs-on: ubuntu-latest

    steps:
      - name: Checkout code
        uses: actions/checkout@v4

      - name: Build auth_service Docker image
        run: |
          docker build -t auth_service:test ./auth_service

      - name: Run auth_service unit tests
        run: |
          docker run --rm auth_service:test pytest -q
